import Head from "next/head";
import "../styles/globals.css";
import type { AppProps } from "next/app";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="bg-gray-200">
        <div className="max-w-6xl px-4 mx-auto border">
          <div className="flex justify-end text-black md:justify-between">
            {/* bottões direita */}
            <div className="hidden py-2 space-x-4 md:flex">
              <div className="px-5 py-2 transition duration-300 bg-yellow-500 rounded-full hover:bg-yellow-400">
                <a href="#" className="flex items-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-6 h-6 mr-1 text-purple-600"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
                    />
                  </svg>
                  <span>Seja um franqueado</span>
                </a>
              </div>
              <div className="px-5 py-2 transition duration-300 bg-indigo-900 rounded-full hover:bg-indigo-800">
                <a href="#" className="flex items-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-6 h-6 mr-1 text-yellow-500"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
                    />
                  </svg>
                  <span>Seja um consultor</span>
                </a>
              </div>
              <div className="px-5 py-2 transition duration-300 bg-blue-400 rounded-full hover:bg-blue-300">
                <a href="#" className="flex items-center">
                  <span>Quero comprar</span>
                </a>
              </div>
            </div>
            {/* bottões esquerdo */}
            <div className="hidden md:block">
              <div className="px-5 py-2 transition duration-300 bg-yellow-500 rounded hover:bg-yellow-400">
                <a href="" className="flex items-center">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    className="w-6 h-6 mr-1"
                    fill="none"
                    viewBox="0 0 24 24"
                    stroke="currentColor"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z"
                    />
                  </svg>
                  <span>Área restrita</span>
                </a>
              </div>
            </div>
            {/* bottões mobile */}
            <div className="flex md:hidden">
              <button>
                <svg
                  xmlns="http://www.w3.org/2000/svg"
                  className="w-6 h-6"
                  fill="none"
                  viewBox="0 0 24 24"
                  stroke="currentColor"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M4 6h16M4 12h16M4 18h16"
                  />
                </svg>
              </button>
            </div>
          </div>
        </div>
        {/* menu mobile */}
        <div>
          <a href="" className="block px-4 py-2 text-sm hover:bg-gray-300">
            Seja um franqueado
          </a>
          <a href="" className="block px-4 py-2 text-sm hover:bg-gray-300">
            Seja um consultor
          </a>
          <a href="" className="block px-4 py-2 text-sm hover:bg-gray-300">
            Quero comprar
          </a>
          <a href="" className="block px-4 py-2 text-sm hover:bg-gray-300">
            Área restrita
          </a>
        </div>
      </nav>

      <Component {...pageProps} />
    </>
  );
}
export default MyApp;
